// <auto-generated />
using System;
using Koinon.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Koinon.Infrastructure.Migrations
{
    [DbContext(typeof(KoinonDbContext))]
    [Migration("20251206041544_AddPasswordHashToPerson")]
    partial class AddPasswordHashToPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Koinon.Domain.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendanceCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("attendance_code_id");

                    b.Property<int?>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.Property<int?>("CheckedOutByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("checked_out_by_person_alias_id");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<int?>("DeclineReasonValueId")
                        .HasColumnType("integer")
                        .HasColumnName("decline_reason_value_id");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<bool?>("DidAttend")
                        .HasColumnType("boolean")
                        .HasColumnName("did_attend");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_time");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<bool>("IsFirstTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_first_time");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("OccurrenceId")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_id");

                    b.Property<int?>("PersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("person_alias_id");

                    b.Property<int?>("PresentByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("present_by_person_alias_id");

                    b.Property<DateTime?>("PresentDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("present_date_time");

                    b.Property<DateTime?>("ProcessedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_date_time");

                    b.Property<int?>("QualifierValueId")
                        .HasColumnType("integer")
                        .HasColumnName("qualifier_value_id");

                    b.Property<int>("RSVP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("rsvp");

                    b.Property<bool>("RequestedToAttend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requested_to_attend");

                    b.Property<bool>("ScheduleConfirmationSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("schedule_confirmation_sent");

                    b.Property<int?>("ScheduledByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("scheduled_by_person_alias_id");

                    b.Property<bool>("ScheduledToAttend")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("scheduled_to_attend");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_time");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceCodeId")
                        .HasDatabaseName("ix_attendance_code_id");

                    b.HasIndex("DidAttend")
                        .HasDatabaseName("ix_attendance_did_attend")
                        .HasFilter("did_attend = true");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_attendance_guid");

                    b.HasIndex("OccurrenceId")
                        .HasDatabaseName("ix_attendance_occurrence_id");

                    b.HasIndex("PersonAliasId")
                        .HasDatabaseName("ix_attendance_person_alias_id");

                    b.HasIndex("StartDateTime")
                        .HasDatabaseName("ix_attendance_start_date_time");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.AttendanceCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<DateTime>("IssueDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issue_date_time");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_attendance_code_code");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_attendance_code_guid");

                    b.HasIndex("IssueDate", "Code")
                        .IsUnique()
                        .HasDatabaseName("uix_attendance_code_issue_date_code");

                    b.ToTable("attendance_code", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.AttendanceOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptConfirmationMessage")
                        .HasColumnType("text")
                        .HasColumnName("accept_confirmation_message");

                    b.Property<int?>("AnonymousAttendanceCount")
                        .HasColumnType("integer")
                        .HasColumnName("anonymous_attendance_count");

                    b.Property<int?>("AttendanceTypeValueId")
                        .HasColumnType("integer")
                        .HasColumnName("attendance_type_value_id");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("DeclineConfirmationMessage")
                        .HasColumnType("text")
                        .HasColumnName("decline_confirmation_message");

                    b.Property<bool?>("DidNotOccur")
                        .HasColumnType("boolean")
                        .HasColumnName("did_not_occur");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("OccurrenceDate")
                        .HasColumnType("date")
                        .HasColumnName("occurrence_date");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<bool>("ShowDeclineReasons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_decline_reasons");

                    b.Property<DateOnly>("SundayDate")
                        .HasColumnType("date")
                        .HasColumnName("sunday_date");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_attendance_occurrence_group_id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_attendance_occurrence_guid");

                    b.HasIndex("LocationId");

                    b.HasIndex("OccurrenceDate")
                        .HasDatabaseName("ix_attendance_occurrence_date");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SundayDate")
                        .HasDatabaseName("ix_attendance_occurrence_sunday_date");

                    b.HasIndex("GroupId", "LocationId", "ScheduleId", "OccurrenceDate")
                        .IsUnique()
                        .HasDatabaseName("uix_attendance_occurrence_group_location_schedule_date");

                    b.ToTable("attendance_occurrence", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampusStatusValueId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_status_value_id");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("LeaderPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("leader_person_alias_id");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ServiceTimes")
                        .HasColumnType("text")
                        .HasColumnName("service_times");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("short_code");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CampusStatusValueId");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_campus_guid");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_campus_is_active");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_campus_order");

                    b.HasIndex("ShortCode")
                        .HasDatabaseName("ix_campus_short_code")
                        .HasFilter("short_code IS NOT NULL");

                    b.ToTable("campus", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.DefinedType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FieldTypeAssemblyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_type_assembly_name");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("HelpText")
                        .HasColumnType("text")
                        .HasColumnName("help_text");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_defined_type_category");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_defined_type_guid");

                    b.HasIndex("IsSystem")
                        .HasDatabaseName("ix_defined_type_is_system");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_defined_type_name");

                    b.ToTable("defined_type", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.DefinedValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<int>("DefinedTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("defined_type_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("DefinedTypeId")
                        .HasDatabaseName("ix_defined_value_defined_type_id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_defined_value_guid");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_defined_value_is_active");

                    b.HasIndex("Order")
                        .HasDatabaseName("ix_defined_value_order");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_defined_value_value");

                    b.HasIndex("DefinedTypeId", "IsActive", "Order")
                        .HasDatabaseName("ix_defined_value_type_active_order");

                    b.ToTable("defined_value", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowGuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_guests");

                    b.Property<int?>("ArchivedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("archived_by_person_alias_id");

                    b.Property<DateTime?>("ArchivedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_date_time");

                    b.Property<int?>("CampusId")
                        .HasColumnType("integer")
                        .HasColumnName("campus_id");

                    b.Property<int?>("CampusId1")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("ExitSystemCommunicationId")
                        .HasColumnType("integer")
                        .HasColumnName("exit_system_communication_id");

                    b.Property<int?>("GroupCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("group_capacity");

                    b.Property<int>("GroupTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("group_type_id");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<bool>("IsSecurityRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_security_role");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_group_id");

                    b.Property<int?>("RequiredSignatureDocumentTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("required_signature_document_template_id");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("StatusValueId")
                        .HasColumnType("integer")
                        .HasColumnName("status_value_id");

                    b.Property<int?>("WelcomeSystemCommunicationId")
                        .HasColumnType("integer")
                        .HasColumnName("welcome_system_communication_id");

                    b.HasKey("Id");

                    b.HasIndex("CampusId")
                        .HasDatabaseName("ix_group_campus_id");

                    b.HasIndex("CampusId1");

                    b.HasIndex("GroupTypeId")
                        .HasDatabaseName("ix_group_group_type_id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_group_guid");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_group_is_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("ix_group_is_archived")
                        .HasFilter("is_archived = false");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_group_name");

                    b.HasIndex("ParentGroupId")
                        .HasDatabaseName("ix_group_parent_group_id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchivedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("archived_by_person_alias_id");

                    b.Property<DateTime?>("ArchivedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_date_time");

                    b.Property<int?>("CommunicationPreference")
                        .HasColumnType("integer")
                        .HasColumnName("communication_preference");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<DateTime?>("DateTimeAdded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_added");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("GroupMemberStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("group_member_status");

                    b.Property<int>("GroupRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("group_role_id");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("InactiveDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inactive_date_time");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsNotified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_notified");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_member_group_id");

                    b.HasIndex("GroupMemberStatus")
                        .HasDatabaseName("ix_group_member_status");

                    b.HasIndex("GroupRoleId")
                        .HasDatabaseName("ix_group_member_group_role_id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_group_member_guid");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_group_member_person_id");

                    b.HasIndex("GroupId", "PersonId", "GroupRoleId")
                        .IsUnique()
                        .HasDatabaseName("uix_group_member_group_person_role")
                        .HasFilter("is_archived = false");

                    b.ToTable("group_member", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.GroupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowGroupSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_group_sync");

                    b.Property<bool>("AllowMultipleLocations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_multiple_locations");

                    b.Property<bool>("AllowSpecificGroupMemberAttributes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_specific_group_member_attributes");

                    b.Property<int?>("ArchivedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("archived_by_person_alias_id");

                    b.Property<DateTime?>("ArchivedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_date_time");

                    b.Property<bool>("AttendanceCountsAsWeekendService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("attendance_counts_as_weekend_service");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<int?>("DefaultGroupRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("default_group_role_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("EnableSpecificGroupRequirements")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enable_specific_group_requirements");

                    b.Property<string>("GroupMemberTerm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Member")
                        .HasColumnName("group_member_term");

                    b.Property<string>("GroupTerm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Group")
                        .HasColumnName("group_term");

                    b.Property<int?>("GroupTypePurposeValueId")
                        .HasColumnType("integer")
                        .HasColumnName("group_type_purpose_value_id");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("IconCssClass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon_css_class");

                    b.Property<bool>("IgnorePersonInactivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ignore_person_inactivated");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsFamilyGroupType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_family_group_type");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.Property<bool>("SendAttendanceReminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("send_attendance_reminder");

                    b.Property<bool>("ShowConnectionStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_connection_status");

                    b.Property<bool>("ShowInGroupList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_in_group_list");

                    b.Property<bool>("ShowInNavigation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_in_navigation");

                    b.Property<bool>("TakesAttendance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("takes_attendance");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_group_type_guid");

                    b.HasIndex("IsFamilyGroupType")
                        .HasDatabaseName("ix_group_type_is_family_group_type")
                        .HasFilter("is_family_group_type = true");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_group_type_name");

                    b.ToTable("group_type", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.GroupTypeRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanEdit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_edit");

                    b.Property<bool>("CanManageMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_manage_members");

                    b.Property<bool>("CanView")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("can_view");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("GroupTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("group_type_id");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsLeader")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_leader");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<int?>("MaxCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_count");

                    b.Property<int?>("MinCount")
                        .HasColumnType("integer")
                        .HasColumnName("min_count");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.Property<bool>("ReceiveRequirementsNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("receive_requirements_notifications");

                    b.HasKey("Id");

                    b.HasIndex("GroupTypeId")
                        .HasDatabaseName("ix_group_type_role_group_type_id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_group_type_role_guid");

                    b.HasIndex("GroupTypeId", "Name")
                        .HasDatabaseName("ix_group_type_role_group_type_id_name");

                    b.ToTable("group_type_role", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("FirmRoomThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("firm_room_threshold");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsGeoPointLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_geo_point_locked");

                    b.Property<double?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<int?>("LocationTypeValueId")
                        .HasColumnType("integer")
                        .HasColumnName("location_type_value_id");

                    b.Property<double?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_location_id");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<int?>("PrinterDeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("printer_device_id");

                    b.Property<int?>("SoftRoomThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("soft_room_threshold");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("Street1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street1");

                    b.Property<string>("Street2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street2");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_location_guid");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_location_is_active");

                    b.HasIndex("LocationTypeValueId")
                        .HasDatabaseName("ix_location_location_type_value_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_location_name");

                    b.HasIndex("ParentLocationId")
                        .HasDatabaseName("ix_location_parent_location_id");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AnniversaryDate")
                        .HasColumnType("date")
                        .HasColumnName("anniversary_date");

                    b.Property<int?>("BirthDay")
                        .HasColumnType("integer")
                        .HasColumnName("birth_day");

                    b.Property<int?>("BirthMonth")
                        .HasColumnType("integer")
                        .HasColumnName("birth_month");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<int?>("CommunicationPreference")
                        .HasColumnType("integer")
                        .HasColumnName("communication_preference");

                    b.Property<int?>("ConnectionStatusValueId")
                        .HasColumnType("integer")
                        .HasColumnName("connection_status_value_id");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Email")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNote")
                        .HasColumnType("text")
                        .HasColumnName("email_note");

                    b.Property<int>("EmailPreference")
                        .HasColumnType("integer")
                        .HasColumnName("email_preference");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<int?>("GivingGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("giving_group_id");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("integer")
                        .HasColumnName("graduation_year");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("InactiveReasonNote")
                        .HasColumnType("text")
                        .HasColumnName("inactive_reason_note");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deceased");

                    b.Property<bool>("IsEmailActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<int?>("MaritalStatusValueId")
                        .HasColumnType("integer")
                        .HasColumnName("marital_status_value_id");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("middle_name");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nick_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("integer")
                        .HasColumnName("photo_id");

                    b.Property<int?>("PrimaryCampusId")
                        .HasColumnType("integer")
                        .HasColumnName("primary_campus_id");

                    b.Property<int?>("PrimaryFamilyId")
                        .HasColumnType("integer")
                        .HasColumnName("primary_family_id");

                    b.Property<int?>("RecordStatusReasonValueId")
                        .HasColumnType("integer")
                        .HasColumnName("record_status_reason_value_id");

                    b.Property<int?>("RecordStatusValueId")
                        .HasColumnType("integer")
                        .HasColumnName("record_status_value_id");

                    b.Property<int?>("RecordTypeValueId")
                        .HasColumnType("integer")
                        .HasColumnName("record_type_value_id");

                    b.Property<string>("ReviewReasonNote")
                        .HasColumnType("text")
                        .HasColumnName("review_reason_note");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("\n                    setweight(to_tsvector('english', coalesce(first_name, '')), 'A') ||\n                    setweight(to_tsvector('english', coalesce(last_name, '')), 'A') ||\n                    setweight(to_tsvector('english', coalesce(nick_name, '')), 'B') ||\n                    setweight(to_tsvector('english', coalesce(email, '')), 'C')\n                    ", true);

                    b.Property<int?>("SuffixValueId")
                        .HasColumnType("integer")
                        .HasColumnName("suffix_value_id");

                    b.Property<string>("SystemNote")
                        .HasColumnType("text")
                        .HasColumnName("system_note");

                    b.Property<int?>("TitleValueId")
                        .HasColumnType("integer")
                        .HasColumnName("title_value_id");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionStatusValueId");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_person_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_person_guid");

                    b.HasIndex("PrimaryCampusId")
                        .HasDatabaseName("ix_person_primary_campus_id");

                    b.HasIndex("PrimaryFamilyId")
                        .HasDatabaseName("ix_person_primary_family_id");

                    b.HasIndex("RecordStatusValueId")
                        .HasDatabaseName("ix_person_record_status_value_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_person_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("ix_person_last_name_first_name");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.PersonAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AliasPersonGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("alias_person_guid");

                    b.Property<int?>("AliasPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("alias_person_id");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int?>("PersonId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_person_alias_guid");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_person_alias_person_id")
                        .HasFilter("person_id IS NOT NULL");

                    b.HasIndex("PersonId1");

                    b.ToTable("person_alias", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("country_code");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("extension");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<bool>("IsMessagingEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_messaging_enabled");

                    b.Property<bool>("IsUnlisted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unlisted");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("number");

                    b.Property<string>("NumberNormalized")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("number_normalized");

                    b.Property<int?>("NumberTypeValueId")
                        .HasColumnType("integer")
                        .HasColumnName("number_type_value_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_phone_number_guid");

                    b.HasIndex("NumberNormalized")
                        .HasDatabaseName("ix_phone_number_normalized");

                    b.HasIndex("NumberTypeValueId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_phone_number_person_id");

                    b.HasIndex("PersonId", "Number")
                        .HasDatabaseName("ix_phone_number_person_number");

                    b.ToTable("phone_number", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_token_expires_at");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_refresh_token_guid");

                    b.HasIndex("PersonId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("uix_refresh_token_token");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoInactivateWhenComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_inactivate_when_complete");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int?>("CheckInEndOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("check_in_end_offset_minutes");

                    b.Property<int?>("CheckInStartOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("check_in_start_offset_minutes");

                    b.Property<int?>("CreatedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_person_alias_id");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EffectiveEndDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_end_date");

                    b.Property<DateOnly?>("EffectiveStartDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_start_date");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("ICalendarContent")
                        .HasColumnType("text")
                        .HasColumnName("icalendar_content");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_public");

                    b.Property<int?>("ModifiedByPersonAliasId")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_person_alias_id");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.Property<int?>("WeeklyDayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("weekly_day_of_week");

                    b.Property<TimeSpan?>("WeeklyTimeOfDay")
                        .HasColumnType("interval")
                        .HasColumnName("weekly_time_of_day");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("uix_schedule_guid");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_schedule_name");

                    b.HasIndex("WeeklyDayOfWeek", "WeeklyTimeOfDay")
                        .HasDatabaseName("ix_schedule_weekly");

                    b.ToTable("schedule", (string)null);
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.AttendanceCode", "AttendanceCode")
                        .WithMany("Attendances")
                        .HasForeignKey("AttendanceCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koinon.Domain.Entities.AttendanceOccurrence", "Occurrence")
                        .WithMany("Attendances")
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koinon.Domain.Entities.PersonAlias", "PersonAlias")
                        .WithMany()
                        .HasForeignKey("PersonAliasId");

                    b.Navigation("AttendanceCode");

                    b.Navigation("Occurrence");

                    b.Navigation("PersonAlias");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.AttendanceOccurrence", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koinon.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koinon.Domain.Entities.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("Location");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Campus", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.DefinedValue", "CampusStatusValue")
                        .WithMany()
                        .HasForeignKey("CampusStatusValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CampusStatusValue");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.DefinedValue", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.DefinedType", "DefinedType")
                        .WithMany("DefinedValues")
                        .HasForeignKey("DefinedTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefinedType");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Group", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.Campus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koinon.Domain.Entities.Campus", null)
                        .WithMany("Groups")
                        .HasForeignKey("CampusId1");

                    b.HasOne("Koinon.Domain.Entities.GroupType", "GroupType")
                        .WithMany("Groups")
                        .HasForeignKey("GroupTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Koinon.Domain.Entities.Group", "ParentGroup")
                        .WithMany("ChildGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koinon.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Groups")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Campus");

                    b.Navigation("GroupType");

                    b.Navigation("ParentGroup");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koinon.Domain.Entities.GroupTypeRole", "GroupRole")
                        .WithMany()
                        .HasForeignKey("GroupRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Koinon.Domain.Entities.Person", "Person")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("GroupRole");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.GroupTypeRole", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.GroupType", "GroupType")
                        .WithMany("Roles")
                        .HasForeignKey("GroupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupType");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Location", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.DefinedValue", "LocationTypeValue")
                        .WithMany()
                        .HasForeignKey("LocationTypeValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koinon.Domain.Entities.Location", "ParentLocation")
                        .WithMany("ChildLocations")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LocationTypeValue");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Person", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.DefinedValue", "ConnectionStatusValue")
                        .WithMany()
                        .HasForeignKey("ConnectionStatusValueId");

                    b.HasOne("Koinon.Domain.Entities.Campus", "PrimaryCampus")
                        .WithMany()
                        .HasForeignKey("PrimaryCampusId");

                    b.HasOne("Koinon.Domain.Entities.Group", "PrimaryFamily")
                        .WithMany()
                        .HasForeignKey("PrimaryFamilyId");

                    b.HasOne("Koinon.Domain.Entities.DefinedValue", "RecordStatusValue")
                        .WithMany()
                        .HasForeignKey("RecordStatusValueId");

                    b.Navigation("ConnectionStatusValue");

                    b.Navigation("PrimaryCampus");

                    b.Navigation("PrimaryFamily");

                    b.Navigation("RecordStatusValue");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.PersonAlias", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koinon.Domain.Entities.Person", null)
                        .WithMany("PersonAliases")
                        .HasForeignKey("PersonId1");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.PhoneNumber", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.DefinedValue", "NumberTypeValue")
                        .WithMany()
                        .HasForeignKey("NumberTypeValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koinon.Domain.Entities.Person", "Person")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NumberTypeValue");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Koinon.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.AttendanceCode", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.AttendanceOccurrence", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Campus", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.DefinedType", b =>
                {
                    b.Navigation("DefinedValues");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Group", b =>
                {
                    b.Navigation("ChildGroups");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.GroupType", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Location", b =>
                {
                    b.Navigation("ChildLocations");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Person", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("PersonAliases");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("Koinon.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
